# Generated by Django 4.1 on 2022-08-05 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urbanizacao", models.CharField(max_length=100)),
                ("rua", models.CharField(max_length=100)),
                ("predio", models.CharField(max_length=10)),
                ("andar", models.CharField(max_length=2)),
                ("entrada", models.CharField(max_length=2)),
                ("numero", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Morador",
            fields=[
                ("nome", models.CharField(max_length=240)),
                ("bi", models.CharField(max_length=15)),
                ("nif", models.CharField(max_length=15)),
                (
                    "numero_de_telefone",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                (
                    "numero_alternativo",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
                ("data_de_nascimento", models.DateField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "local_de_trabalho",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("funcionario_publico", models.BooleanField(default=False)),
                (
                    "habitacao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="baia_farta.habitacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("numero_contrato", models.CharField(max_length=20)),
                (
                    "tipo_de_renda",
                    models.CharField(
                        choices=[("RES", "Resoluvel"), ("ARR", "Arrendamento")],
                        default="ARR",
                        max_length=3,
                    ),
                ),
                ("inicio_de_contrato", models.DateField()),
                (
                    "morador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="baia_farta.morador",
                    ),
                ),
            ],
        ),
    ]
