# Generated by Django 4.1 on 2022-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baia_farta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitacao",
            name="bloco",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
