# Generated by Django 4.1 on 2022-08-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("baia_farta", "0002_habitacao_bloco"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="habitacao",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="baia_farta.habitacao",
            ),
            preserve_default=False,
        ),
    ]
